version: "3.9"

services:
  application:
    build: .
    container_name: esacademy-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      CLOUD_AWS_REGION: ${CLOUD_AWS_REGION}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      CLOUD_AWS_BUCKET_NAME: ${CLOUD_AWS_BUCKET_NAME}
      SECURITY_JWT_SECRET_KEY: ${SECURITY_JWT_SECRET_KEY}
      SECURITY_JWT_EXPIRATION_EXPIRATION_TIME: ${SECURITY_JWT_EXPIRATION_EXPIRATION_TIME}
      RESEND_API_KEY: ${RESEND_API_KEY}
      ADMIN_CRED_USERNAME: ${ADMIN_CRED_USERNAME}
      ADMIN_CRED_PASSWORD: ${ADMIN_CRED_PASSWORD}
      ADMIN_CRED_EMAIL: ${ADMIN_CRED_EMAIL}



  postgres:
    image: postgres
    container_name: esacademy_db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
