spring.application.name=edusolution

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

# jwt
security.jwt.secret-key = ${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time = ${SECURITY_JWT_EXPIRATION_EXPIRATION_TIME}

# cors
cors.allowed-origins=http://localhost:5173
cors.allowed-methods=POST,GET,PUT,DELETE,OPTIONS
cors.allowed-headers=Content-Type,X-Request-ID
cors.allow-credentials=true
